baseURL = 'https://www.jeffvansteijn.nl/'
languageCode = 'en-us'
title = 'Jeff van Steijn'
theme = 'renegade'
publishDir = "public"



[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = "-110"
  [[menu.main]]
    identifier = "posts"
    name = "Post"
    url = "/posts/"
    weight = -200